###服务启动端口号
server:
  port: 8700
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

spring:
  application:
    name:  app-shop-integral
  #  zipkin:
  #    base-url: http://127.0.0.1:9411/
  #    ###全部采集
  #  sleuth:
  #    sampler:
  #      probability: 1.0
  redis:
    host: 192.168.25.142
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  ###数据库相关连接
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.142:3306/meite_integral?useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
    ####连接地址
    host: 127.0.0.1
    ####端口号
    port: 5672
    ####账号
    username: root
    ####密码
    password: 123456
    ### 连接的虚拟主机名称,类似mysql中的哪个数据库
    virtual-host: /rabbit_test
    listener:
      simple:
        retry:
          ####开启消费者重试（程序出现异常的情况下会进行重试）
          enabled: true
          ####最大重试次数
          max-attempts: 5
          ####重试间隔时间3s
          initial-interval: 3000
        ####开启手动ack
        acknowledge-mode: manual
        default-requeue-rejected: false
####打印MyBatias日志
logging:
  level:
    ### 开发环境使用DEBUG 生产环境info或者error
    com.mayikt.member.mapper: DEBUG


