###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-shop-weixin
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

      swagger:
        base-package: com.shop.service
        title: SpringCloud2.x微服务电商项目-微信服务接口
        description:
        version: 1.1
        terms-of-service-url: www.hutao.fun
        contact:
          name: hutao
          email: 247486412@qq.com
