eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
server:
  port: 80
shop:
  zuul:
    swagger:
      document: |-
        [
            {
                "name": "app-shop-member",
                "location": "/app-shop-member/v2/api-docs",
                "version": "2.0"
            },
            {
                "name": "app-shop-weixin",
                "location": "/app-shop-weixin/v2/api-docs",
                "version": "2.0"
            }
        ]
spring:
  application:
    name: app-shop-zuul
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.142:3306/shop-gateway?useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 192.168.25.142
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
zuul:
  routes:
    api-a:
      path: /app-weixin/**
      serviceId: app-shop-weixin
    api-b:
      path: /app-member/**
      serviceId: app-shop-member
    api-c:
      path: /app-pay/**
      serviceId: app-shop-pay
    api-d:
      path: /app-auth/**
      serviceId: app-shop-authorization
    api-e:
      path: /public/app-pay/**
      serviceId: app-shop-pay
    api-f:
      path: /app-seckill/**
      serviceId: app-shop-seckill
