eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka
      swagger:
        base-package: com.shop.serviceApi
        contact:
          email: 247486412@qq.com
          name: hutao
        description: SpringCloud2.x微服务电商项目-微信服务接口
        terms-of-service-url: www.hutao.fun
        title: SpringCloud2.x微服务电商项目-微信服务接口
        version: 1.1
logging:
  level:
    com:
      github:
        binarywang:
          demo:
            wx:
              mp: DEBUG
    me:
      chanjar:
        weixin: DEBUG
    org:
      springframework:
        web: INFO
server:
  port: 8200
shop:
  weixin:
    default:
      registration:
        code:
          message: 您的消息，我们已经收到,会及时回复给您的!
    registration:
      code:
        message: 您的注册码为:%s,感谢关注!
spring:
  application:
    name: app-shop-weixin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.25.142:3306/shop-user?useSSL=false&characterEncoding=utf-8
    username: root
  redis:
    database: 0
    host: 192.168.25.142
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: -1
        min-idle: 1
    password: 123456
    port: 6379
wx:
  mp:
    configs:
      - appId: wxdfd88049d64088f6
        secret: c31364303e23a86e7b7f9136c8759e47
        token: shop
###设置feign客户端超时时间默认feign请求超过1s就超时,SpringCloud feign 默认开启支持ribbon
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000
